# Generated by Django 4.1.2 on 2022-12-07 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=144)),
                ('answer', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set_question', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=144)),
                ('price', models.IntegerField()),
                ('final_date', models.DateField(default=datetime.datetime(2022, 12, 14, 21, 53, 46, 628562))),
                ('highest_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set_item', to=settings.AUTH_USER_MODEL)),
                ('question_id_array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ID_set', to='auction.questions')),
            ],
        ),
    ]
