# Generated by Django 4.1.3 on 2022-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_rename_questions_question_alter_item_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='question_id_array',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
