# Generated by Django 4.1.3 on 2022-12-13 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 21, 19, 47, 554340)),
        ),
    ]
