# Generated by Django 4.1.3 on 2022-12-14 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_item_final_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='./static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 15, 27, 58, 72470)),
        ),
    ]
