# Generated by Django 4.1.3 on 2022-12-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_delete_image_item_picture_alter_item_final_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 15, 59, 34, 689792)),
        ),
    ]
