# Generated by Django 4.1.3 on 2022-12-14 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_item_image_name_alter_item_final_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 16, 30, 27, 179799)),
        ),
    ]
