# Generated by Django 4.1.3 on 2022-12-14 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_user_image_name_alter_item_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 17, 39, 2, 968940)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./static/default_item.jpg', null=True, upload_to='./static'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./static/default.jpg', null=True, upload_to='./static'),
        ),
    ]
