# Generated by Django 4.1.2 on 2022-12-14 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_item_final_date_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 19, 29, 58, 911644)),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./auction/static/default_item.jpg', null=True, upload_to='./auction/static'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./auction/static/default.jpg', null=True, upload_to='./auction/static'),
        ),
    ]
