# Generated by Django 4.1.2 on 2022-12-15 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_alter_item_final_date_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 13, 56, 9, 508741)),
        ),
    ]
