# Generated by Django 4.1.3 on 2022-12-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_item_email_sent_alter_item_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 16, 43, 56, 230957)),
        ),
    ]
