# Generated by Django 4.1.2 on 2022-12-16 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 0, 22, 56, 210040)),
        ),
    ]
