# Generated by Django 4.1.2 on 2022-12-16 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_item_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 1, 34, 47, 511634)),
        ),
    ]
