# Generated by Django 4.1.3 on 2022-12-07 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_questions_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='highestBidder',
            new_name='highest_bidder',
        ),
        migrations.RemoveField(
            model_name='item',
            name='finalDate',
        ),
        migrations.AddField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 8, 59, 20, 393437)),
        ),
    ]
