# Generated by Django 4.1.3 on 2022-12-07 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_highestbidder_item_highest_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 10, 32, 58, 93589)),
        ),
    ]
