# Generated by Django 4.1.3 on 2022-12-05 11:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../uploads/profile_pic_default.jpg', upload_to='./uploads'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=uuid.uuid4, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=30),
        ),
    ]
